version: '3.8'

services:
  sip-client:
    build:
      context: .
      dockerfile: deployment/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./deployment/web:/usr/share/nginx/html
      - ./deployment/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/nginx/ssl
    restart: unless-stopped
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    networks:
      - sip-network

networks:
  sip-network:
    driver: bridge 